/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ClassList;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testClassList() {
        ClassList classlist = new ClassList();
        Student student = new Student("Program", 4, 70.5);
        classlist.students.add(student);
        assertNotNull(classlist.students.get(0).getProgram());
        assertNotNull(classlist.students.get(0).getYear());
        assertNotNull(classlist.students.get(0).getGrade());
    }
}
